Feature/nite owl
chirpradio/cloud-functions pull request #46
Opened 2024-07-31 03:14 UTC by bmcdonn2

Initial offering for capturing nite-owl tracks played by the automation software. Includes the following features:

- A live DJ cooldown, the intent here is to disregard any tracks played by the automation if a recent play from a DJ has been detected. Should cover situations where the morning DJ leaves automation running while playing their own tracks.
- Track search to locate relevant categories, label and album information using iterative method for track title
- Creation of playlist event using /freeform endpoint available in NextUp API

There are a few additional changes that could be part of this particular PR, primarily a new node script to handle deployments to dev google cloud platform accounts. I also still need to figure out how to limit access the the cloud function by IP but that occurs withing GCP itself so it may not be something captured in this code. 

Beyond that, there are some improvements that I'd like to implement in the future. The main one being an improvement to how we handle the DJ cooldown where we can inspect the most recently played DJ track and using it's duration with playlist event time to calculate if it could still be playing. Minor improvements would be how logging is handled and some of the error handling.

2024-08-01 13:52 UTC, bmcdonn2 commented on nite-owl/lib/logging.js
Just wanted to note that this isn't being used right now but I didn't want to completely remove the file as I do want improve logging in the future.

2024-08-12 00:13 UTC, lund5000 requested changes

2024-08-12 00:13 UTC, lund5000 commented on nite-owl/lib/trackSearch.service.js
> +const DURATION_TOLERANCE_MS = 30000;
Could do with a comment around here to explain the discrepancy in duration you found between the Track entities in the library and StationPlaylist

2024-08-13 01:42 UTC, bmcdonn2 commented on nite-owl/lib/createPlaylistEvent.js
> +const AUTOMATION_USER_ID = process.env.AUTOMATION_USER_ID ?? "5820844800999424";
That value is currently just the ID of the automation user in dev. Figured it would be safe as a fallback but maybe it would be more appropriate to discard that in favor of letting the corresponding checks fail so that we know some env variable is missing?

2024-08-13 01:45 UTC, bmcdonn2 commented on nite-owl/lib/createPlaylistEvent.js
> +  if (!req.query.api_key) {
Yeah, I was hoping I could handle this similar to how an express middleware would work but that sort of thing isn't supported for HTTP cloud functions. A standalone method is probably the best middle ground.

2024-08-13 01:51 UTC, bmcdonn2 commented on nite-owl/lib/createPlaylistEvent.js
> +    if (djPlay !== undefined && djPlay !== null) {
The way that this is written now will cause a delay in capturing the first track based on the `DJ_PLAY_COOLDOWN_MINUTES`. So if a DJ plays a track at 11:59, we won't begin capturing until 12:19. 

I know it isn't ideal, but the alternatives are the switch that we've discussed in the past or using that recently played track to inform us on how long the cooldown should be. The issue with using the recent playlist event is that duration is not included so we'd need an additional lookup to grab that value and perform the calculation.

Given our current state is not capturing any automation information, I thought this hardcoded cooldown period was a good enough compromise for now. At the cost of missing some a track or two when the night DJ leaves, we gain some insurance against a morning DJ leaving the automation running for an hour.

2024-08-13 04:08 UTC, bmcdonn2 commented on nite-owl/lib/nextup.service.js
> +    const response = await instance.post(`/playlist/freeform`, data);
Do you have any guidance on how to use the `/playlsit/track` endpoint? I've tried using the `id` and `__key` values returned in the track search for the `artist`, `album` and `track` but they don't appear to work. I also took a look at the underlying model but I can't make sense of what it is expecting https://github.com/chirpradio/nextup/blob/develop/app/services/playlistevent.service.js#L15-L16

2024-08-16 00:19 UTC, bmcdonn2 commented on nite-owl/lib/nextup.service.js
> +    const response = await instance.post(`/playlist/freeform`, data);
Alright I figured it out. The logic will now use the `/playlist/track` endpoint when the track was located via search.

2024-08-21 00:01 UTC, lund5000 approved these changes

2024-09-06 14:49 UTC, merged